- id: '1773043826190'
  alias: Контроль разряда АКБ
  description: ''
  triggers:
  - type: battery_level
    device_id: 37c5b1b4b36e4785b64988b356132bc9
    entity_id: 859362503f3c3af800aef0daadc57ad0
    domain: sensor
    trigger: device
    below: 95
  conditions: []
  actions:
  - type: turn_on
    device_id: 8607d806741df3b9d09d3b3d88c57278
    entity_id: 28bb0c728251ed85f5ff51462ccc98e2
    domain: switch
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: Включена Зарядка АКБ
      title: Дозоряд
  mode: single
- id: '1773402115915'
  alias: Вкл подсветку
  description: ''
  triggers:
  - type: turned_on
    device_id: 3bbc0a9646885842fbdc9b0c8a161d69
    entity_id: 497876cfc73b39fe25de940609533074
    domain: remote
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: 05651cea72f58a10e68a03c425b53415
    entity_id: 6e241b535b029d776fe10066b6d06084
    domain: light
  mode: single
- id: '1773402170996'
  alias: Выкл подсветку
  description: ''
  triggers:
  - type: turned_off
    device_id: 3bbc0a9646885842fbdc9b0c8a161d69
    entity_id: 497876cfc73b39fe25de940609533074
    domain: remote
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: 05651cea72f58a10e68a03c425b53415
    entity_id: 6e241b535b029d776fe10066b6d06084
    domain: light
  mode: single
- id: '1773438993649'
  alias: Питание восстановлено
  description: ''
  triggers:
  - entity_id: switch.zariadka_akb_socket_1
    from: unavailable
    trigger: state
  conditions: []
  actions:
  - data:
      title: ✅ Электричество восстановлено
      message: Питание вернулось, розетка снова в сети.
    action: notify.persistent_notification
  mode: single
- id: '1773439262901'
  alias: AВР вкл
  description: ''
  triggers:
  - entity_id:
    - switch.zariadka_akb_socket_1
    to:
    - unavailable
    trigger: state
  conditions: []
  actions:
  - action: notify.mobile_app_satana_android
    data:
      title: ⚡ Аварийное питание
      message: "\U0001F6A8 Включено аварийное питание!\n\n\U0001F552 {{ now().strftime('%H:%M
        %d.%m.%Y') }}\n"
  mode: single
- id: '1773439346327'
  alias: АВР выкл
  description: ''
  triggers:
  - entity_id: switch.zariadka_akb_socket_1
    from: unavailable
    trigger: state
  conditions: []
  actions:
  - action: notify.mobile_app_satana_android
    data:
      title: ✅ Электричество восстановлено
      message: "Питание вернулось!\n\n\U0001F552 {{ now().strftime('%H:%M %d.%m.%Y')
        }}\n"
  mode: single
- id: '1773491451717'
  alias: "\U0001F6A8 Сирена на телефоне"
  triggers:
  - entity_id: alarm_control_panel.alarmo
    to: triggered
    trigger: state
  actions:
  - action: notify.mobile_app_000
    data:
      data:
        channel: alarm_stream
        importance: max
        ttl: 0
        priority: high
      title: "\U0001F6A8 ТРЕВОГА!"
      message: Сработала сигнализация!
  - data:
      title: "\U0001F6A8 ТРЕВОГА!"
      message: Сработала сигнализация!
      data:
        channel: alarm_stream
        importance: max
        ttl: 0
        priority: high
    action: notify.mobile_app_satana_android
  - action: notify.mobile_app_redmi_note_9_pro
    data:
      data:
        channel: alarm_stream
        importance: max
        ttl: 0
        priority: high
      message: Сработала сигнализация!
      title: "\U0001F6A8 ТРЕВОГА!"
  - action: notify.mobile_app_ludmilla
    data:
      message: Сработала сигнализация!
      title: "\U0001F6A8 ТРЕВОГА!"
      data:
        channel: alarm_stream
        importance: max
        ttl: 0
        priority: high
- id: '1773636286016'
  alias: Обработка callback Статус
  description: ''
  triggers:
  - event_type: telegram_callback
    event_data:
      data: /lights
    trigger: event
  actions:
  - action: telegram_bot.send_message
    metadata: {}
    data:
      entity_id:
      - notify.svet_zp_bot_cicada3301_1144785510
  mode: single
- id: '1773639843520'
  alias: Telega
  description: Отправляет красивое меню с состоянием дома при команде /start
  triggers:
  - event_type: telegram_command
    event_data:
      command: /start
    trigger: event
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      chat_id: 1144785510
      parse_mode: markdown
      inline_keyboard:
      - "\U0001F4A1 Свет:/lights, \U0001F50C Розетки:/sockets"
      - "\U0001F50B АКБ:/battery, \U0001F321️ Погода:/weather"
      - "\U0001F504 Статус:/status"
      config_entry_id: 01KKMEPQ2JEMB1ATAXVMNQ8KVQ
      message: "\U0001F4A1 *Освещение* \n• Свет: {{ states('switch.svet_switch_1')
        | replace('on','ВКЛ ✅') | replace('off','ВЫКЛ \U0001F7E5') }}  \n• Стенка
        LED: {{ states('light.stenku') | replace('on','Горит \U0001F31F') | replace('off','Выкл
        \U0001F311') }}  \n\n\U0001F50B *Батареи и АКБ*  \n• JK-BMS ёмкость: {{ states('sensor.jk_bms_capacity_remaining')
        | float(0) | round(0) }}%  \n• JK-BMS напряжение: {{ states('sensor.jk_bms_total_voltage')
        | float(0) | round(2) }} В  \n• JK-BMS ток: {{ states('sensor.jk_bms_current')
        | float(0) | round(1) }} А  \n• JK-BMS мощность: {{ states('sensor.jk_bms_power')
        | float(0) | round(0) }} Вт  \n• Зарядка АКБ: {{ 'Заряжается ⚡' if is_state('switch.zariadka_akb_socket_1','on')
        else 'Отключено ❌' }}  \n\n\U0001F324️ *Погода*  Температура: {{ state_attr('weather.forecast_home_assistant',
        'temperature') | float(0) | round(0) }}°C"
      message_tag: '3301'
  mode: single
